function [ pathName ] = createPathNameForTestAndConditions( flowParameters, pivParameters )
%Helper function for defining output path name
%   Detailed explanation goes here

    pathName = ['Bits' num2str(pivParameters.bits, '%02d') filesep ...        
        'DeltaXFactor' num2str(flowParameters.deltaXFactor, '%1.2f') filesep ...
        'Ni' num2str(pivParameters.Ni, '%02d') filesep ...
        flowParameters.flowType filesep ...
        'ParticleRadius' num2str(pivParameters.particleRadius, '%1.2f') ...
        '_Noise' num2str(pivParameters.noiseLevel, '%02d') ...
        '_Thickness' num2str(pivParameters.laserSheetThickness, '%02d') ...
        '_Deviation' num2str(pivParameters.outOfPlaneStdDeviation, '%1.3f') ];
end

